### ISSUE TITLE
[BUG] Serialization endpoint and createAASXAASEnvironmentSerialization methods unable to download and include files

### ISSUE THREAD

**Issue by StenGruener** [eclipse-basyx/basyx-java-server-sdk#353]
**Describe the bug**
Both tried serialization methods fail to download/include attached files into the serialized AASX file. An exception is trown and the file content downloaded via serialization endpoint is empty.

**To Reproduce**
1. Upload attached file into aas-env (rename zip to aasx)
2. Open ui
3. Click on download button (null.aasx) in the aas list
4. See error log, instpect AAS in package explorer there is no attached file

**Expected behavior**
Files should be downloaded and included in the output.

**BaSyx (please complete the following information):**
- BaSyx Version [2.0.0-snapshot]
- BaSyx SDK [Java]
- AAS Version [DotAAS V3]

**Screenshots**
[file-bug.zip](https://github.com/user-attachments/files/16348575/file-bug.zip)

**Used Asset Administration files (.aasx/.json/.xml)**
Please drop your AAS files here that were used when the bug was encountered.

**Additional context**
![image](https://github.com/user-attachments/assets/1dacd628-e906-423e-b21e-8cd8371c7ba2)
![image](https://github.com/user-attachments/assets/8c3fe5ab-15e0-41ef-9bce-a00c46279832)

**Comment by mateusmolina-iese** [comment]
Hi @StenGruener,

thanks for raising the issue. We will take a look at the provided example and get back to you.

**Comment by StenGruener** [comment]
@mateusmolina-iese  thanks! Also, Files seem to be broken in general (looks like this is some kind of a regression, since it was fixed in 1.5) - the value contains like /tmp/<somestring>filename which is not a downloadable URI I would expect as an AAS client.

**Comment by aaronzi** [comment]
I can also reproduce this bug when downloading an AAS as a .aasx file using the `serialization` endpoint.

Regarding file handling during runtime, we provide the standardized `attachment` endpoints for uploading/updating, downloading and deleting files from (file) submodelElements (see screenshot).
![image](https://github.com/user-attachments/assets/9f3bb165-bc7d-4bac-83fb-494b0b027361)

**Comment by StenGruener** [comment]
@aaronzi thanks, but this also happens when proper AASes are loaded. So i am sure it is not based on the missing idshort, correct?

**Comment by aaronzi** [comment]
You are right, this also happens with any other AAS. It seems as this was never implemented.

**Comment by StenGruener** [comment]
any indication when/if it gonna be implemented?

**Comment by aaronzi** [comment]
We have added this to our backlog. I cannot give you any specifics. I will update you as soon as we have implemented this.

If you need this urgently, please send me an email so we can discuss how to proceed.

**Comment by aaronzi** [comment]
You're welcome. I can't give any specifics but soon ;)

**Comment by StenGruener** [comment]
@aaronzi Hi Aaron, it is unfortunatelly still failing in conjunction with ConnectedSubmodelService
![image](https://github.com/user-attachments/assets/24cf4cd0-9d8e-4fed-bd6e-10ef194464ef)

https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/97f5be874fbb6fd343e618fcf21af26973d2ea87/basyx.submodelservice/basyx.submodelservice-client/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/client/ConnectedSubmodelService.java#L211

Do i see that this could whould construct the attachment url (ending with /attachment) and create a file based on that url? Any hope to get this one fixed?
